# Setup
title:               Swayam Chube
tagline: 	            
url:                 https://swayamchube.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Swayam Chube

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
